### ISSUE TITLE
Pass command line params to the make tool

### ISSUE THREAD

**Issue by nzakas** [arturadib/shelljs#188]
I'm using the make tool, and I'd like to be able to pass in command line arguments to it. I tried this:

```
$ node Makefile.js client-test -- foo.js
no such target: --
no such target: foo
```

It seems that all parameters are treated as potential targets. Would it be possible to use `--` as a delimiter to pass in command line arguments?

**Comment by gregglind** [comment]
(this is similar to the solution npm run-script uses, for what it's worth).

Edge cases here... should the args go to *each* target?

**Comment by gregglind** [comment]
@nzakas, here is a mostly equivalent drop-in for `shelljs/make`:  https://gist.github.com/gregglind/fc11df28d4d8702c7eef

**Comment by nzakas** [comment]
@arturadib any interest in this? I can make a pull request if so.

**Comment by arturadib** [comment]
@nzakas sounds good to me.. I like that there's a precedent in `npm run-script`. mind adding a note about it in the README too? thanks!

**Comment by arturadib** [comment]
@nzakas oh also, please @-mention me in the PR as my notifications are mostly muted these days :)

**Comment by nzakas** [comment]
Will do, thanks!

**Comment by Frikki** [comment]
May I ask, what’s the status?
