### ISSUE TITLE
Enter text to prompt

### ISSUE THREAD

**Issue by sean-hill** [arturadib/shelljs#203]
Hey there,

I'm trying to automate a build process for Android apps with gulp. Here is the gulp task I have wrapped around `shelljs`:

	gulp.task('jarsign-android', function(callback){
		var command = 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release-key.keystore <path-to-apk> release';
		sh.exec(command, callback);
	});

However the `jarsigner` command asks for the password to the keystore file with a prompt:

    Enter Passphrase for keystore:

Is there a way to pipe in commands from the terminal while using the `sh.exec` command?

**Comment by iolufemi** [comment]
+1

**Comment by iolufemi** [comment]
Save your passphrase in a file, eg. passkey.txt 

Then use the command like this;

```sh
var command = 'jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release-key.keystore <path-to-apk> release < passkey.txt';
```

**Comment by sean-hill** [comment]
Sweet thanks!
