### ISSUE TITLE
Execute a file

### ISSUE THREAD

**Issue by DmitryEfimenko** [arturadib/shelljs#211]
I have a `.sh` file to be executed. Is there a way to do that with shelljs?
Below does not work on Windows:
```
var scriptToRun = path.resolve('./', 'shells/', 'myScript.sh');
shell.exec(scriptToRun, { async: true })
```
**myScript.sh**
```
#!/bin/sh

VAR1="asd"
echo $VAR1
```

**Comment by snuggles08** [comment]
_No._ shelljs is not an _interpreter_ (something that executes code directly), it allows you to write shell-script (`.sh`) _styled_ scripts in _Node.js_. Windows does not come with an shell-script _interpreter_.
