### ISSUE TITLE
cd into home directory

### ISSUE THREAD

**Issue by wayneashleyberry** [arturadib/shelljs#9]
``` cd('~'); ```

Just returns an error :(

``` cd: no such file or directory: ~ ```

**Comment by wayneashleyberry** [comment]
Closed due to inactivity.

**Comment by nfischer** [comment]
@wayneashleyberry Although this is already closed, I thought I'd ping the thread to say that this has been implemented in v0.6

**Comment by wayneashleyberry** [comment]
oh awesome, thanks @nfischer :)
